baseURL = 'https://hartwich.cc'
languageCode = 'de-de'
title = 'Mein Blog'
theme = 'hello-friend-ng'

[params]
  # Standard-Farbschema (dark oder light)
  defaultTheme = "dark"
  # Menü-Anzeige
  showMenuItems = 5

[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts/"
  weight = 10
